In [1]:
!pip install -r ../requirements.txt

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\gusta\appdata\roaming\python\python313\site-packages (from -r ../requirements.txt (line 1)) (3.0.2)
Requirement already satisfied: numpy in c:\users\gusta\appdata\roaming\python\python313\site-packages (from -r ../requirements.txt (line 2)) (2.4.4)
Requirement already satisfied: scikit-learn in c:\users\gusta\appdata\roaming\python\python313\site-packages (from -r ../requirements.txt (line 3)) (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gusta\appdata\roaming\python\python313\site-packages (from pandas->-r ../requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\gusta\appdata\roaming\python\python313\site-packages (from pandas->-r ../requirements.txt (line 1)) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\gusta\appdata\roaming\python\python313\site-packages (from scikit-learn->-r ../requirements.txt (line 3)) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\gusta\appdata\roaming\python\python313\site-packages (from scikit-learn->-r ../requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\gusta\appdata\roaming\python\python313\site-packages (from scikit-learn->-r ../requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\gusta\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas->-r ../requirements.txt (line 1)) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler

In [3]:
#arquivo limpO
caminho_dados = '../data/train_clean.csv' 
df = pd.read_csv(caminho_dados)

# printa dimensão e as primeiras linhas
print("Dimensão do dataset:", df.shape)
df.head()

Dimensão do dataset: (1000, 72)

,fifa_rank,fifa_points,wins_last_10_matches,losses_last_10_matches,draws_last_10_matches,win_rate_last_year,goals_scored_avg,goals_conceded_avg,clean_sheets_last_10,shots_per_game,...,country_code_SEN,country_code_SRB,country_code_SUI,country_code_SWE,country_code_TUN,country_code_TUR,country_code_UKR,country_code_URU,country_code_USA,country_code_WAL
0,18,1675.2,5,4,1,0.520,1.11,0.91,3,11.3,...,0,0,0,0,0,0,0,0,0,0
1,8,1831.2,7,2,1,0.690,2.31,0.76,5,19.2,...,0,0,0,0,0,0,0,0,0,0
2,6,1769.3,6,2,2,0.585,1.85,0.62,3,15.9,...,0,0,0,0,0,0,0,0,0,0
3,17,1663.4,7,1,2,0.584,1.40,1.09,2,15.6,...,0,0,0,0,0,0,0,0,0,0
4,28,1476.6,3,5,2,0.390,0.95,1.97,2,6.2,...,0,0,0,0,0,0,0,0,0,0

In [4]:
#O target é a coluna winner, que indica o vencedor de cada jogo
y = df['winner']

# Retiramos a winner do dataset para criar o x 
X = df.drop(columns=['winner'])

print("Formato de X:", X.shape, "| Formato de y:", y.shape)
X.head()

Formato de X: (1000, 71) | Formato de y: (1000,)

,fifa_rank,fifa_points,wins_last_10_matches,losses_last_10_matches,draws_last_10_matches,win_rate_last_year,goals_scored_avg,goals_conceded_avg,clean_sheets_last_10,shots_per_game,...,country_code_SEN,country_code_SRB,country_code_SUI,country_code_SWE,country_code_TUN,country_code_TUR,country_code_UKR,country_code_URU,country_code_USA,country_code_WAL
0,18,1675.2,5,4,1,0.520,1.11,0.91,3,11.3,...,0,0,0,0,0,0,0,0,0,0
1,8,1831.2,7,2,1,0.690,2.31,0.76,5,19.2,...,0,0,0,0,0,0,0,0,0,0
2,6,1769.3,6,2,2,0.585,1.85,0.62,3,15.9,...,0,0,0,0,0,0,0,0,0,0
3,17,1663.4,7,1,2,0.584,1.40,1.09,2,15.6,...,0,0,0,0,0,0,0,0,0,0
4,28,1476.6,3,5,2,0.390,0.95,1.97,2,6.2,...,0,0,0,0,0,0,0,0,0,0

In [ ]:

#binarizando o nome dos paises usando onehot encoding e evitando redundancias com o drop_first=true
X_encoded = pd.get_dummies(X, drop_first=True)
colunas_x = X_encoded.columns

print("Novas colunas em X_encoded:", X_encoded.shape[1])
X_encoded.head()

Novas colunas em X_encoded: 71

,fifa_rank,fifa_points,wins_last_10_matches,losses_last_10_matches,draws_last_10_matches,win_rate_last_year,goals_scored_avg,goals_conceded_avg,clean_sheets_last_10,shots_per_game,...,country_code_SEN,country_code_SRB,country_code_SUI,country_code_SWE,country_code_TUN,country_code_TUR,country_code_UKR,country_code_URU,country_code_USA,country_code_WAL
0,18,1675.2,5,4,1,0.520,1.11,0.91,3,11.3,...,0,0,0,0,0,0,0,0,0,0
1,8,1831.2,7,2,1,0.690,2.31,0.76,5,19.2,...,0,0,0,0,0,0,0,0,0,0
2,6,1769.3,6,2,2,0.585,1.85,0.62,3,15.9,...,0,0,0,0,0,0,0,0,0,0
3,17,1663.4,7,1,2,0.584,1.40,1.09,2,15.6,...,0,0,0,0,0,0,0,0,0,0
4,28,1476.6,3,5,2,0.390,0.95,1.97,2,6.2,...,0,0,0,0,0,0,0,0,0,0

In [ ]:

scaler = StandardScaler()
colunas_x = X_encoded.columns
X_escalonado = scaler.fit_transform(X_encoded)  
X_final = pd.DataFrame(X_escalonado, columns=colunas_x)

print("escalonamento concluído. primeiras linhas de X_final:")  
X_final.head()

escalonamento concluído. primeiras linhas de X_final:

,fifa_rank,fifa_points,wins_last_10_matches,losses_last_10_matches,draws_last_10_matches,win_rate_last_year,goals_scored_avg,goals_conceded_avg,clean_sheets_last_10,shots_per_game,...,country_code_SEN,country_code_SRB,country_code_SUI,country_code_SWE,country_code_TUN,country_code_TUR,country_code_UKR,country_code_URU,country_code_USA,country_code_WAL
0,-0.320421,0.116190,0.043901,0.335341,-0.592790,0.000853,-0.664274,-0.645424,0.213678,-0.259079,...,-0.139169,-0.149983,-0.135388,-0.14646,-0.114766,-0.110208,-0.114766,-0.139169,-0.153432,-0.149983
1,-1.016533,1.164301,0.913237,-0.712599,-0.592790,1.036502,1.565705,-0.996490,1.347251,2.022414,...,-0.139169,-0.149983,-0.135388,-0.14646,-0.114766,-0.110208,-0.114766,-0.139169,-0.153432,-0.149983
2,-1.155756,0.748416,0.478569,-0.712599,0.132779,0.396836,0.710880,-1.324152,0.213678,1.069385,...,-0.139169,-0.149983,-0.135388,-0.14646,-0.114766,-0.110208,-0.114766,-0.139169,-0.153432,-0.149983
3,-0.390032,0.036910,0.913237,-1.236569,0.132779,0.390744,-0.125362,-0.224144,-0.353108,0.982746,...,-0.139169,-0.149983,-0.135388,-0.14646,-0.114766,-0.110208,-0.114766,-0.139169,-0.153432,-0.149983
4,0.375692,-1.218137,-0.825434,0.859310,0.132779,-0.791114,-0.961604,1.835445,-0.353108,-1.731943,...,-0.139169,-0.149983,-0.135388,-0.14646,-0.114766,-0.110208,-0.114766,-0.139169,-0.153432,-0.149983

In [7]:
# Juntamos tudo para exportar num único arquivo
dataset_pronto = X_final.copy()
dataset_pronto['winner'] = y.values 

# Salva o arquivo
dataset_pronto.to_csv('../data/train_engineered.csv', index=False)
print("'train_engineered.csv' salvo com sucesso!")

'train_engineered.csv' salvo com sucesso!

In [ ]:
#APLICANDO A MESMA LOGICA DAS CELULAS ANTERIORES NO ARQUIVO DE TESTE



# Carregar o arquivo de teste limpo
df_test = pd.read_csv('../data/test_clean.csv')


print("Dimensão do dataset de teste:", df_test.shape)

# Separar X e y caso o arquivo de teste possua a coluna 'winner'
if 'winner' in df_test.columns:
    X_test_raw = df_test.drop(columns=['winner'])
    y_test = df_test['winner']
else:
    X_test_raw = df_test
    y_test = None

# Transformação Categórica
X_test_encoded = pd.get_dummies(X_test_raw, drop_first=True)

# Garante que o teste tenha as mesmas colunas que o treino

X_test_encoded = X_test_encoded.reindex(columns=colunas_x, fill_value=0)

# Escalonamento
X_test_escalonado = scaler.transform(X_test_encoded)

# Transformamos de volta para um DataFrame 
X_test_final = pd.DataFrame(X_test_escalonado, columns=colunas_x)

# Salvar o arquivo final
dataset_teste_pronto = X_test_final.copy()
if y_test is not None:
    dataset_teste_pronto['winner'] = y_test.values 

# Salvamos na pasta data com um novo nome
dataset_teste_pronto.to_csv('../data/test_engineered.csv', index=False)
print("Arquivo 'test_engineered.csv' processado e salvo com sucesso!")

Dimensão do dataset de teste: (250, 69)
Arquivo 'test_engineered.csv' processado e salvo com sucesso!